#!/usr/bin/env bash

APP="game_room"

BUILD_HOST="robolia"
BUILD_USER="deploy"
BUILD_AT="/var/www/robolia/build"

PRODUCTION_HOSTS="robolia"
PRODUCTION_USER="deploy"
DELIVER_TO="/var/www/robolia/release"

pre_erlang_get_and_update_deps() {
  local _prod_secret_path="/var/www/robolia/config/prod.secret.exs"
  local _rel_config_path="/var/www/robolia/config/rel_config.exs"
  local _github_key_path="/var/www/robolia/config/github_key_dockerfiles"
  if [ "$TARGET_MIX_ENV" = "prod" ]; then
    __sync_remote "
      ln -sfn '$_prod_secret_path' '$BUILD_AT/config/prod.secret.exs' && \
      ln -sfn '$_rel_config_path' '$BUILD_AT/rel/config.exs' && \
      ln -sfn '$_github_key_path' '$BUILD_AT/priv/dockerfiles/github-ssh'
    "
  fi
}

pre_erlang_clean_compile() {
  if [ "$TARGET_MIX_ENV" = "prod" ]; then
    status "Compiling assets" # log output prepended with "----->"
    __sync_remote " # runs the commands on the build host
      [ -f ~/.profile ] && source ~/.profile

      set -e # fail if any command fails (recommended)

      cd '$BUILD_AT'

      cd assets/
      npm install
      npm run deploy
      cd -

      mkdir -p priv/static # required by the phoenix.digest task
      APP='$APP' MIX_ENV='$TARGET_MIX_ENV' $MIX_CMD phx.digest $SILENCE
    "
  fi
}
