FROM elixir:1.6.4-slim as builder

RUN apt-get -qq update && \
    apt-get -qq install git

ADD ./github-ssh /root/.ssh/id_rsa

RUN mkdir -p ~/.ssh && \
    echo "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config && \
    chmod 700 /root/.ssh/id_rsa

WORKDIR /app

ARG player_repo_url

RUN git clone $player_repo_url . && mix compile
